let products = [
  {
    id: 1,
    name: "Nike Air Max",
    url: "./assets/img1.png",
    price: "14,000",
    size: "18 UK",
    inn: "TRUE",
  },
  {
    id: 2,
    name: "Air Jordan V - 'The Fighter'",
    url: "./assets/img2.png",
    price: "16,600",
    size: "16 UK",
    inn: "TRUE",
  },
  {
    id: 3,
    name: "Nike Air Force 1 Shadow",
    url: "./assets/img3.png",
    price: "23,566",
    size: "12 UK",
    inn: "FALSE",
  },
  {
    id: 4,
    name: "Nike Air Force 1 '07",
    url: "./assets/img4.png",
    price: "11,000",
    size: "18 UK",
  },
  {
    id: 5,
    name: " Nike Air Zoom Pegasus FlyEase",
    url: "./assets/img5.png",
    price: "14,600",
    size: "16 UK",
    inn: "FALSE",
  },
  {
    id: 6,
    name: "Air Jordan 5 Retro 'Green Bean'",
    url: "./assets/img6.png",
    price: "21,999",
    size: "15 UK",
    inn: "FALSE",
  },
  {
    id: 7,
    name: "Nike Dunk Low Retro Premium",
    url: "./assets/img7.png",
    price: "8,799",
    size: "22 UK",
    inn: "TRUE",
  },
  {
    id: 8,
    name: "Nike Air Force 1 Mid '07 QS",
    url: "./assets/img8.png",
    price: "10,999",
    size: "16 UK",
    inn: "TRUE",
  },
  {
    id: 9,
    name: " Nike Air Zoom Pegasus FlyEase1",
    url: "./assets/img9.png",
    price: "24,000",
    size: "18 UK",
    inn: "TRUE",
  },
  {
    id: 10,
    name: " Nike Air Zoom Pegasus 39",
    url: "./assets/img10.png",
    price: "10,500",
    inn: "TRUE",
    size: "22 UK",
  },
  {
    id: 11,
    name: "Nike ZoomX Invincible Run ",
    url: "./assets/img11.png",
    price: "7000",
    size: "22 UK",
  },
  {
    id: 12,
    name: "Nike ZoomX Invincible Run 1",
    url: "./assets/img12.png",
    price: "7000",
    inn: "FALSE",
    size: "16 UK",
  },
  {
    id: 13,
    name: "Nike ZoomX Invincible Run 2",
    url: "./assets/img13.png",
    price: "7000",
    inn: "FALSE",
    size: "15 UK",
  },
  {
    id: 14,
    name: "Nike ZoomX Invincible Run 3",
    url: "./assets/img14.png",
    price: "7000",
    inn: "FALSE",
    size: "16 UK",
  },
];

export default products;
